### ISSUE TITLE
Enhancement in Speech to Text 

### ISSUE THREAD

**Issue by reddymahendra52** [code-value/code-hack#65]
* I know there is already a speech to text file in projects but its only python code which is hard to understand for beginners so I
  created this file with a really good and understandable markdown with how to install and write their first speech to text code.
* The markdown contains photos also for better understanding
* And a jupyter notebook with code is also provided and the a live working video is also provided.

**Comment by reddymahendra52** [comment]
Can I start working??

**Comment by code-value** [comment]
make a pr, will be merged only after review

**Comment by reddymahendra52** [comment]
Created PR #69
